### ISSUE TITLE
Meson supported architectures - tracking issue

### ISSUE THREAD

**Issue by mtsokol** [HaoZeke/OpenBLAS#19]
Here's a tracking issue for OpenBLAS Meson supported architectures:

### x86_64
- [x] `haswell` - https://github.com/HaoZeke/OpenBLAS/pull/17
- [x] `sandybridge` - https://github.com/HaoZeke/OpenBLAS/pull/17
- [x] `skylakex` - https://github.com/HaoZeke/OpenBLAS/pull/17
- [x] `zen` - https://github.com/HaoZeke/OpenBLAS/pull/17
- [ ] `nehalem`
- [ ] `barcelona`
- [ ] `cooperlake`
- [ ] `penryn`
- [ ] `prescott`
- [ ] `...`

### arm64
- [x] `armv8` - https://github.com/HaoZeke/OpenBLAS/pull/17
- [ ] `armv8sve`
- [ ] `a64fx`
- [ ] `cortexa53`
- [ ] `cortexa55`
- [ ] `...`

### riscv64
- [ ] `c910v`
- [ ] `riscv64_generic`
- [ ] `...`

### PPC
- [ ] ...

**Comment by HaoZeke** [comment]
The ones @mtsokol has done so far are all the available (but transient in some cases) runners from GHA. We might need to look into other CI services for the rest..

**Comment by rgommers** [comment]
Question: was leaving out AVX512 on purpose? There is no compile check or an attempt to define any of the `HAVE_AVX512` support. 

My guess is yes it was on purpose and left for later (and we may have discussed it), but I'm not sure.

**Comment by mtsokol** [comment]
I think I worked on minimal setup here for these architectures (that they can be build and tests are passing), so I didn't look into AVX512 while working on it. So I think we left it for later.
