### ISSUE TITLE
Meson tests migration - tracking issue

### ISSUE THREAD

**Issue by mtsokol** [HaoZeke/OpenBLAS#5]
Hi @HaoZeke,

Here's a tracking issue for OpenBLAS tests. So far I found test-like files in these directories. Check-mark indicates that this directory has been ported:

- [x] `test` - https://github.com/HaoZeke/OpenBLAS/pull/7
- [x] `ctest` - https://github.com/HaoZeke/OpenBLAS/pull/8
- [x] `utest` - https://github.com/HaoZeke/OpenBLAS/pull/6 // https://github.com/HaoZeke/OpenBLAS/pull/10
- [ ] `cpp_thread_test`
- [x] `lapack-netlib/BLAS/TESTING`
- [ ] `lapack-netlib/CBLAS/testing`
- [ ] `lapack-netlib/TESTING`
- [ ] `relapack/test`

I'm not sure if all of them need to be ported.

**Comment by HaoZeke** [comment]
Excellent, I think we can definitely skip `relapack` for now, and perhaps even the `netlib` tests (for a first pass).

**Comment by mtsokol** [comment]
Ok, we have three PRs right now that port `test`, `ctest`, and `utest`.
